language: perl
sudo: false

install:
  - perlbrew list
  - cpanm -n Dist::Zilla App::af FFI::Platypus
  - af missing | cpanm
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing   | cpanm -n

perl:
  - "5.28"
  - "5.30"

script:
  - dzil test -v

env:
  global:
    - PERL_USE_UNSAFE_INC=0
  matrix:
    - ALIEN_INSTALL_TYPE=share
    - ALIEN_INSTALL_TYPE=system
